In [1]:
import numpy as np
import pandas as pd

In [5]:
# Exercise 1: Create and reshape a numpy array
arr1 = np.arange(1, 11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
arr1 = arr1.reshape(2, 5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
# Exercise 2: Extract elements from index 5 to 15
arr2 = np.arange(1, 21)
print(arr2)
extracted = arr2[5:16]
print(extracted)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15 16]


In [41]:
# Exercise 3: Create and modify a Pandas Series
fruit_series = pd.Series([3,2,1],index=["apple","bananas","Oranges"])
print(fruit_series)

apple      3
bananas    2
Oranges    1
dtype: int64


In [43]:
fruit_series["pears"] = 4
print(fruit_series)

apple      3
bananas    2
Oranges    1
pears      4
dtype: int64


In [45]:
# Exercise 4: Create a dataframe with name, age, gender
data = {
    'name': ["Arun", "Binu", "Chandran", "Deepak", "Esha", "Faisal", "Gopal", "Haritha", "Indrajith", "Jayan"],
    'age': [25, 30, 27, 35, 22, 40, 29, 31, 28, 33],
    'gender': ["Male", "Male", "Male", "Male", "Female", "Male", "Male", "Female", "Male", "Male"]
}
df = pd.DataFrame(data)
print(df)


        name  age  gender
0       Arun   25    Male
1       Binu   30    Male
2   Chandran   27    Male
3     Deepak   35    Male
4       Esha   22  Female
5     Faisal   40    Male
6      Gopal   29    Male
7    Haritha   31  Female
8  Indrajith   28    Male
9      Jayan   33    Male


In [47]:
# Exercise 5: Add a new column 'occupation'
df['occupation'] = ["Programmer", "Manager", "Analyst", "Programmer", "Manager", "Analyst", "Programmer", "Manager", "Analyst", "Programmer"]
print(df)

        name  age  gender  occupation
0       Arun   25    Male  Programmer
1       Binu   30    Male     Manager
2   Chandran   27    Male     Analyst
3     Deepak   35    Male  Programmer
4       Esha   22  Female     Manager
5     Faisal   40    Male     Analyst
6      Gopal   29    Male  Programmer
7    Haritha   31  Female     Manager
8  Indrajith   28    Male     Analyst
9      Jayan   33    Male  Programmer


In [49]:
# Exercise 6: Select rows where age >= 30
filtered_df = df[df['age'] >= 30]
print(filtered_df)

      name  age  gender  occupation
1     Binu   30    Male     Manager
3   Deepak   35    Male  Programmer
5   Faisal   40    Male     Analyst
7  Haritha   31  Female     Manager
9    Jayan   33    Male  Programmer


In [51]:
# Exercise 7: Convert dataframe to CSV and read it back
df.to_csv("dataframe.csv", index=False)
read_df = pd.read_csv("dataframe.csv")
print(read_df)

        name  age  gender  occupation
0       Arun   25    Male  Programmer
1       Binu   30    Male     Manager
2   Chandran   27    Male     Analyst
3     Deepak   35    Male  Programmer
4       Esha   22  Female     Manager
5     Faisal   40    Male     Analyst
6      Gopal   29    Male  Programmer
7    Haritha   31  Female     Manager
8  Indrajith   28    Male     Analyst
9      Jayan   33    Male  Programmer
